#+TITLE:     Meteorological Data Sources
#+AUTHOR:    Oscar Perpiñán Lamigueiro

* Climate and Meteorological Observations
  :PROPERTIES:
  :CUSTOM_ID: observations
  :END:

** Ground Stations
*** World
- [[http://www.bsrn.awi.de/][Baseline Surface Radiation Network]]

*** España
- [[http://eportal.magrama.gob.es/websiar/Inicio.aspx][MAGRAMA-SIAR]]
- [[http://www.aemet.es/es/eltiempo/observacion/ultimosdatos][AEMET]]
- [[http://www2.meteogalicia.es/galego/observacion/estacions/estacions.asp#][Meteogalicia]]
- [[http://meteo.navarra.es/estaciones/descargardatos.cfm][MeteoNavarra]]
- [[http://www.meteo.cat/xema/AppJava/SeleccioPerComarca.do][MeteoCat]]
- [[http://crea.uclm.es/siar/datmeteo/][Castilla - La Mancha]]
- [[http://www.meteoclimatic.com/][Meteoclimatic]]
- [[http://www.tiempodiario.com/][Tiempo Diario]]

*** USA
- [[http://www.nrel.gov/midc/][Measurement and Instrumentation Data Center NREL (NREL-MIDC)]]




** SSE-NASA
- 200 satellite-derived meteorology and solar energy parameters
  *monthly averaged* from 22 years of data
- Resolución 1ºx1º

[[https://eosweb.larc.nasa.gov/cgi-bin/sse/sse.cgi]]


** Integrated Climate Data Center

The [[http://icdc.zmaw.de/icdc_home.html?&L=1][CliSAP-Integrated Climate Data Center]] (ICDC) allows easy
access to climate relevant data from in-situ measurements and
satellite remote sensing. These data are important to determine
the status and the changes in the climate system. Additionally
some relevant re-analysis data are included, which are modeled on
the basis of observational data.

*** Coverage, spatial and temporal resolution

- Period: 07/2006 to 02/2011
- Temporal resolution: Monthly

- Coverage and spatial resolution:

    + Global
    + Spatial resolution: 2° x 2°, cartesian grid
    + Geographic longitude: -180°E to 180°E
    + Geographic latitude: -90°E to 90°E
    + Dimension: 180 columns x 90 rows for total ("total") cloud cover, and coverage of high ("high"), middle ("mid") and low level ("low") clouds; 180 columns x 90 rows x 40 levels for product "profile"
    + Altitude: variable for "total", "high", "mid", and "low"; every 480 m for "profile"

- Format: NetCDF

*** [[http://icdc.zmaw.de/icdc_home.html?&L=1][Solar Irradiance]]

CM-SAF (see below).

*** [[http://icdc.zmaw.de/calipso-cloudsat_cloudcover.html?&L=1][Cloud Cover]] 

This data set is only available for a restricted user
group. [[http://icdc.zmaw.de/beratung.html?&L=1][Contact]].

This data set is based on observations of two vertically profiling
  satellite sensors: a radar (CloudSat) and a lidar
  (CALIPSO-CALIOP). The CloudSat radar operates at a frequency of 94
  GHz (wavelength: about 2 mm). The CALIPSO lidar operates with three
  channels: two at 532 nm which perpendicular to each other
  polarization and one at 1064 nm.

  
** NCDC-NOAA

[[http://www.ncdc.noaa.gov/][NOAA’s National Climatic Data Center]] (NCDC) maintains the world's
largest climate data archive and provides climatological services
and data to every sector of the United States economy and to users
worldwide. Records in the archive range from paleoclimatic data to
centuries-old journals to data less than an hour old. The Center's
mission is to preserve these data and make them available to the
public, business, industry, government, and researchers.


*** Satellite data

The National Oceanic and Atmospheric Administration (NOAA) manages
a [[http://www.ncdc.noaa.gov/satellite-data][constellation of geostationary and polar-orbiting meteorological
spacecrafts]]. These satellites are distributed among three
operational programs: the Suomi NPOESS Preparatory Project (NPP),
the Geostationary Operational Environmental Satellite Program
(GOES), and the Polar Operational Environmental Satellite Program
(POES). The Defense Meteorological Satellite Program (DMSP)
satellites are operated by the U.S. Department of Defense and the
data are archived and distributed by NOAA's National Climatic Data
Center (NCDC) under the Shared Processing Program.

- The International Satellite Cloud Climatology
  Project ([[http://isccp.giss.nasa.gov/][ISCCP]]) provides global cloud information at many
  resolutions (32 to 280km) and time scales (3 hourly to monthly)
  derived from geostationary and polar orbiting satellite
  instruments.  Global; varying resolution 1983–2009

- Climate Data Record Program Gridded Satellite (GridSat) from
  ISCCP B1 Infrared (IR) window channel brightness
  temperatures. Data have been calibrated and remapped to gridded
  netCDF.  70N-70S; 8km 3 hourly; 1981-2009


** CALIPSO

The Cloud-Aerosol Lidar and Infrared Pathfinder Satellite
Observation (CALIPSO) satellite provides new insight into the role
that clouds and atmospheric aerosols (airborne particles) play in
regulating Earth's weather, climate, and air quality.

CALIPSO combines an active lidar instrument with passive infrared
and visible imagers to probe the vertical structure and properties
of thin clouds and aerosols over the globe. CALIPSO was launched
on April 28, 2006 with the cloud profiling radar system on the
CloudSat satellite.

CALIPSO and CloudSat are highly complementary and together provide
new, never-before-seen 3-D perspectives of how clouds and aerosols
form, evolve, and affect weather and climate. CALIPSO and CloudSat
fly in formation with three other satellites in the A-train
constellation to enable an even greater understanding of our
climate system from the broad array of sensors on these other
spacecraft.

*** [[http://eosweb.larc.nasa.gov/PRODOCS/calipso/table_calipso.html][Data products]]

Extracted from [[http://www-calipso.larc.nasa.gov/products/CALIPSO_DPC_Rev3x5.pdf][Document No: PC-SCI-503]].

Lidar Level 1 data values consist of geolocated profiles of
calibrated lidar return signals. Level 1 IIR and WFC data consist
of calibrated radiances. 

There are three types of Lidar Level 2 products: layer products
(cloud and aerosol), profile products (backscatter and extinction)
and a vertical feature mask (cloud and aerosol locations and
type). IIR Level 2 products are provided based on the IIR Swath
(all pixels across swath) and IIR Track (coincident with lidar
footprints). The Lidar Level 2 cloud layer products are produced
at three horizontal resolutions: 1/3 km, 1 km, and 5 km. The Lidar
Level 2 aerosol layer products are produced at a 5 km horizontal
resolution. The cloud and aerosol layer data products are written
in Hierarchical Data Format (HDF).

Lidar Level 3 products contain monthly-averaged parameters that
are mapped onto a uniform spatial grid.

The highest quality data products generated by the DMS are
referred to as Standard data products. These products have a 2-4
day latency to incorporate the global meteorological and other
reference products. 

The CALIPSO project has also developed several special products
such as an Expedited Level 1.5 near-real time product released to
operational forecast centers and a Lidar Level 3 Aerosol data
product. The Expedited Level 1.5 data set is a merged product
using the Lidar Level 1 data, Level 2 Aerosol profiles and Level 2
Vertical Feature Mask information. It provides continuous,
calibrated and geo-located profiles of cloud-cleared data. The
Lidar Level 3 Aerosol data product is a monthly-averaged data set
derived using Lidar Level 2 products and maps aerosol parameters
onto a uniform space and time grid and employs various filtering
options.

Data can be freely ordered from [[http://eosweb.larc.nasa.gov/HBDOCS/langley_web_tool.html][NASA ASDC]].

*** [[http://cloudsat.atmos.colostate.edu/][CloudSat]]

CloudSat is a satellite mission designed to measure the vertical
structure of clouds from space. The radar data produces detailed
images of cloud structures which will contribute to a better
understanding of clouds and climate. Please peruse this website to
find out more about the CloudSat mission and the Data Processing
Center.  

*** [[http://www.cloudsat.cira.colostate.edu/dataHome.php][Products]]:

CloudSat data products are made available in HDF-EOS format and
are created with HDF-EOS 2.5 based on HDF 4.1r2. Data is available
after registration from the [[http://www.cloudsat.cira.colostate.edu/data_dist/OrderData.php][CloudSat Data Processing Center]].

- 1B-CPR-FL: Radar Backscatter Profiles (First-Look)
- 1B-CPR: Radar Backscatter Profiles
- 2B-GEOPROF: Cloud Geometrical Profile
- 2B-CLDCLASS: Cloud Classification 
- 2B-CWC-RO: Cloud Water Content (Radar-only) (includes liquid and ice)
- 2B-TAU: Cloud Optical Depth
- 2B-CWC-RVOD: Cloud Water Content (Radar-Visible Optical Depth) (includes liquid and ice)
- 2B-FLXHR: Fluxes and Heating Rates
- 2B-GEOPROF-LIDAR: Radar-Lidar Cloud Geometrical Profile
- 2B-CLDCLASS-LIDAR: Radar-Lidar Cloud Classification 


** EUMETSAT

[[http://www.eumetsat.int][EUMETSAT]] operates a fleet of meteorological satellites, and their
related ground systems, to deliver reliable and cost-efficient
data, images and products. These, in turn, service requirements
for weather and climate monitoring — primarily of national
meteorological services in the Member- and Cooperating States.

There are several [[http://www.eumetsat.int/Home/Main/DataProducts/ProductNavigator/index.htm?l=en][data products]] available:

*** Atmosphere

- [[http://navigator.eumetsat.int/discovery/Start/DirectSearch/Extended.do?freeTextValue%2528resourceidentifier%2529=EO:EUM:DAT:MSG:AMV][Atmospheric Motion Vectors]]

Atmospheric Motion Vectors at all heights below the tropopause,
derived from 5 channels (Visual 0.8, Water Vapour 6.2, Water
Vapour 7.3, Infrared 10.8 and the High Resolution Visual channel),
all combined into one product. Vectors are derived by tracking the
motion of clouds and other atmospheric constituents as water
vapour patterns. The initial resolution is a 24 pixels grid (HRV
12 high res. pixels), but as the algorithm tries to adjust the
position to the point of the maximum contrast (typically cloud
edges), the end resolution varies. The height assignment of the
AMVs is calculated using the Cross-Correlation Contribution (CCC)
function to determine the pixels that contribute the most to the
vectors. An AMV product contains between 30 000 and 50 000 vectors
depending of the time of the day, and uses SEVERI image data from
Meteosat-8 and onwards (24 per day).

- [[http://navigator.eumetsat.int/discovery/Start/DirectSearch/Extended.do?freeTextValue%2528resourceidentifier%2529=EO:EUM:DAT:MSG:CSR][Clear Sky Radiances]]

The Clear-Sky Radiances (CSR) product is a subset of the
information derived during the Scenes Analysis processing. The
product provides the radiances for a subset of the MSG channels
averaged over all pixels within a processing segment which have
been identified as clear, except for channel WV6.2 where the CSR
is also derived for areas containing low-level clouds. The final
CSR product is BUFR encoded at every third quarter of the hour
(e.g 00:45, 01:45 ...) and distributed to the users via EUMETCAST
and GTS. It is also stored in the EUMETSAT Data
Centre. Applications and Users: Numerical weather prediction

- [[http://navigator.eumetsat.int/discovery/Start/DirectSearch/Extended.do?freeTextValue%2528resourceidentifier%2529=EO:EUM:DAT:MSG:CLA][Cloud Analysis]] 

Identification of cloud layers with cloud type and coverage,
height and temperature. Applications and Users: Weather
forecasting, numerical weather prediction, climate research and
monitoring. (24 per day)

- [[http://navigator.eumetsat.int/discovery/Start/DirectSearch/Extended.do?freeTextValue%2528resourceidentifier%2529=EO:EUM:DAT:MSG:OCA][Optimal Cloud Analysis]]

The basic premise of the scheme is that best quality products are
derived when all the information in the measurements is used,
properly accounting for errors in the measurements and supporting
data, and making use of physical radiative transfer
calculations. In the current configuration, the 0.6, 0.8, 1.6,
10.8 and 12 µm channels are employed to estimate cloud optical
depth, phase and cloud particle size and pressure on a
pixel-by-pixel basis. This will soon be extended to include the
3.9, 8.7 and 13 µm channels and pixel fractional cloud
cover. Coded as a prototype system by RAL in 2001, the 'Optimal
Cloud Analysis' scheme is now under development at EUMETSAT with
the aim to provide potential 'Day-2' products from the MSG SEVIRI
instrument.

- [[http://smsc.cnes.fr/IASI/][IASI]]

The main objective of the Infrared Atmospheric Sounding
Interferometer (IASI) is to provide high resolution atmospheric
emission spectra to derive temperature and humidity profiles with
high spectral and vertical resolution and accuracy. Additionally
it is used for the determination of trace gases, as well as land
and sea surface temperature, emissivity and cloud properties. The
Cloud Parameters (CLP) product contains fractional cloud cover,
cloud top pressure and temperature and cloud phase, retrieved from
the IASI sounder measurements. The spatial sampling is ca. 25 km
at nadir. 

- [[http://navigator.eumetsat.int/discovery/Query/Detail.do?fileIdentifier=EO%253AEUM%253ADAT%253AMFG%253ACMW1&pageId=brief_BROWSER_QUERY_FRAME&history=catalogHistory][Cloud Motion Winds]]

This product is a high-quality subset of the ELW product. The
winds are derived for all three spectral channels (VIS in half
resolution) as for the ELW Product. However, the CMW product only
includes the best wind for each segment determined from the QI
value. There are other limitations, specified in the dissemination
limit table. A typical product will contain up to 750 winds per
channel. The product is distributed for the synoptic hours of 00,
06, 12 and 18 UTC in SATOB code. (16 per day)


*** [[http://www.eumetsat.int/Home/Main/DataProducts/Land/index.htm?l=en][Land]]

- [[http://navigator.eumetsat.int/discovery/Start/DirectSearch/Extended.do?freeTextValue%2528resourceidentifier%2529=EO:EUM:DAT:MSG:LST-SEVIRI][Land Surface Temperature]]

Land Surface Temperature (LST) is the radiative skin temperature
over land. LST plays an important role in the physics of land
surface as it is involved in the processes of energy and water
exchange with the atmosphere. LST is useful for the scientific
community, namely for those dealing with meteorological and
climate models. Accurate values of LST are also of special
interest in a wide range of areas related to land surface
processes, including meteorology, hydrology, agrometeorology,
climatology and environmental studies.

- [[http://navigator.eumetsat.int/discovery/Start/DirectSearch/Extended.do?freeTextValue%2528resourceidentifier%2529=EO:EUM:DAT:METOP:OAS012][ASCAT Winds and Soil Moisture at 12.5 km Swath Grid]]

This ASCAT Multi-parameter product contains surface wind vectors
over ocean and soil moisture index over land. Additionally, the
backscatter values involved in the retrieval of the geophysical
parameters above are also included, as well as several quality
flags to facilitate the use of the data. For NWP users this
product is provided in BUFR format. The netCDF version of this
product contains Winds ONLY.

- [[http://navigator.eumetsat.int/discovery/Query/Detail.do?fileIdentifier=EO%253AEUM%253ADAT%253AMETOP%253AAVHRRL1&pageId=brief_BROWSER_QUERY_FRAME&history=catalogHistory][Advanced Very High Resolution Radiometer]]

The Advanced Very High Resolution Radiometer (AVHRR) operates at 5
different channels simultaneously in the visible and infrared
bands, with wavelengths specified in the instrument channels
description. Channel 3 switches between 3a and 3b for daytime and
nighttime. As a high-resolution imager (about 1.1 km near nadir)
its main purpose is to provide cloud and surface information such
as cloud coverage, cloud top temperature, surface temperature over
land and sea, and vegetation or snow/ice. In addition, AVHRR
products serve as input for the level 2 processing of IASI and
ATOVS. (15 per day, ~1Gb)


** CM SAF

*** Description
The [[http://www.cmsaf.eu/][Satellite Application Facility on Climate Monitoring]] (CM SAF)
is a joint venture of the Royal Netherlands Meteorological
Institute, the Swedish Meteorological and Hydrological Institute,
the Royal Meteorological Institute of Belgium, the Finnish
Meteorological Institute, the Deutscher Wetterdienst, Meteoswiss,
the UK MetOffice, with the collaboration of the European
Organization for the Exploitation of Meteorological Satellites
(EUMETSAT). The CM SAF was funded in 1992 to retrieve, archive,
and distribute climate data to be used for climate monitoring and
climate analysis. The spatial resolution of the different products
ranges from 15 to 90 km².

*** Products
The CM SAF provides two categories of data: operational products
and climate data. The operational products are built on data that
is validated with on-ground stations and then is provided in near
real time to develop variability studies in diurnal and seasonal
time scales. However, climate data are long-term data series to
assess inter-annual variability.

The Operational Products are divided in four classes:

- [[http://wui.cmsaf.eu/safira/action/viewProduktList?id=1][Clouds]]
  + Fractional cloud cover
  + Cloud optical depth
  + Cloud phase
  + Cloud top height
  + Cloud top pressure
  + Cloud top temperature
  + Cloud type
  + Cloud water path
- [[http://wui.cmsaf.eu/safira/action/viewProduktList?id=2][Surface radiation]]
  + Surface albedo
  + Surface downward longwave radiation
  + Surface incoming direct radiation
  + Surface incoming shortwave radiation
  + Surface net longwave radiation
  + Surface net shortwave radiation
  + Surface outgoing longwave radiation
  + Surface radiation budget
- [[http://wui.cmsaf.eu/safira/action/viewProduktList?id=3][Radiation fluxes at the top of the atmosphere]]
  + Emitted thermal radiative flux at top of atmosphere
  + Incoming solar radiative flux at top of atmosphere
  + Reflected solar radiative flux at top of atmosphere
- [[http://wui.cmsaf.eu/safira/action/viewProduktList?id=5][Water vapour and temperature products]]
  + Water vapour, temperature and rel. humidity at 5 layers
  + Temperature and specific humidity at 6 pressure levels
  + Vertically integrated water vapour

These products are available at daily and monthly temporal
resolutions. Some of the equivalent climate data sets are
available with hourly temporal resolutions.

The data provision is free of charge from the [[http://wui.cmsaf.eu/][Web User Interface]].


** LSA SAF

[[http://landsaf.meteo.pt/][Land Surface Analysis Satellite Applications Facility]]

The main purpose of the Land SAF is to increase the benefits from
MSG and EPS data related to land, land-atmosphere interactions and
biophysical applications, namely by developing techniques,
products and algorithms that will allow a more effective use of
data from the two planned EUMETSAT satellites.  Although directly
designed to improve the observation of meteorological systems, the
spectral characteristics, time resolution and global coverage
offered by MSG and EPS allow for their use in a broad spectrum of
other applications, namely within the scope of land biophysical
applications.

Activities to be performed within the framework of the Land SAF
shall involve the development of products that are especially
relevant in the following fields of application:

- Weather forecasting and climate modelling, which require
  detailed information on the nature and properties of
  land. Highest Land SAF priority should be towards the
  meteorological community and, within that community, NWP has
  been already identified as the one that has the greatest
  potential of fully exploit the products;
- Environmental management and land use, which require information
  on land cover type and land cover changes (e.g. provided by
  biophysical parameters or thermal characteristics);
- Natural hazards management, which requires frequent observations
  of terrestrial surfaces in both the solar and thermal bands;
- Climatological applications and climate change detection.




** MODIS

*** Description
The Moderate-resolution Imaging Spectroradiometer (MODIS) is a
payload scientific instrument launched into Earth orbit by NASA in
1999 on board the Terra (EOS AM) Satellite, and in 2002 on board
the Aqua (EOS PM) satellite. The instruments capture data in 36
spectral bands ranging in wavelength from 0.4 µm to 14.4 µm and at
varying spatial resolutions (2 bands at 250 m, 5 bands at 500 m
and 29 bands at 1 km). Together the instruments image the entire
Earth every 1 to 2 days. They are designed to provide measurements
in large-scale global dynamics including changes in Earth's cloud
cover, radiation budget and processes occurring in the oceans, on
land, and in the lower atmosphere. Three on-board calibrators (a
solar diffuser combined with a solar diffuser stability monitor, a
spectral radiometric calibration assembly, and a black body)
provide in-flight calibration. 

*** Products
There are six Level-2 (Orbital Swath) [[http://modis-atmos.gsfc.nasa.gov/MOD06_L2/index.html][MODIS Atmosphere]] products
collected from two platforms: the Terra platform and the Aqua
platform. Each product is assigned an 8-character Earth Science Data
Type (ESDT) name, given below, which is used in cataloging and
archiving the datasets. The Level-2 MODIS Atmosphere products are:

- The [[http://modis-atmos.gsfc.nasa.gov/MOD04_L2/index.html][Aerosol Product]] monitors aerosol type, aerosol optical
  thickness, particle size distribution, aerosol mass
  concentration, optical properites, and radiative forcing. The
  ESDT names are MOD04_L2 (Terra) and MYD04_L2 (Aqua).


- The [[http://modis-atmos.gsfc.nasa.gov/MOD05_L2/index.html][Water Vapor Product]] monitors atmospheric water vapor and
  precipitable water. The ESDT names are MOD05_L2 (Terra) and MYD05_L2 (Aqua).


- The [[http://modis-atmos.gsfc.nasa.gov/MOD06_L2/index.html][Cloud Product]] monitors the physical and radiative properties
  of clouds including cloud particle phase (ice vs. water, clouds
  vs. snow), effective cloud particle radius, cloud optical
  thickness, cloud shadow effects, cloud top temperature, cloud
  top height, effective emissivity, cloud phase (ice vs. water,
  opaque vs. non-opaque), and cloud fraction under both daytime
  and nighttime conditions. The ESDT names are MOD06_L2 (Terra)
  and MYD06_L2 (Aqua).


- The [[http://modis-atmos.gsfc.nasa.gov/MOD07_L2/index.html][Atmosphere Profile Product]] monitors profiles of atmospheric
  temperature and moisture, atmospheric stability, and total ozone
  burden. The ESDT names are MOD07_L2 (Terra) and MYD07_L2 (Aqua).


- The [[http://modis-atmos.gsfc.nasa.gov/MOD35_L2/index.html][Cloud Mask Product]] indicates whether a given instrument
  field of view (FOV) of the Earth's surface is unobstructed by
  clouds or affected by cloud shadows. The cloud mask also
  provides additional information about the FOV including the
  presence of: cirrus clouds, ice/snow, and sunglint
  contamination. Finally flags denoting day/night and land/water
  are included. The ESDT names are MOD35_L2 (Terra) and MYD35_L2 (Aqua).


- The post-launch [[http://modis-atmos.gsfc.nasa.gov/JOINT/index.html][Joint Atmosphere Product]] contains a spectrum of
  key parameters gleaned from the complete set of standard
  at-launch Level 2 products: Aerosol, Water Vapor, Cloud,
  Profile, and Cloud Mask. The Joint Atmosphere product was
  designed to be small enough to minimize data transfer and
  storage requirements, yet robust enough to be useful to a
  significant number of MODIS data users. Scientific data sets
  (SDS's) contained within the Joint Atmosphere product cover a
  full set of high-interest parameters produced by the MODIS
  Atmosphere group, and are stored at 5-km and 10-km (at nadir)
  spatial resolutions. The ESDT names are MODATML2 (Terra) and
  MYDATML2 (Aqua).

MODIS Data is distributed free of charge through the Level 1 and
Atmosphere Archive and Distribution System ([[http://ladsweb.nascom.nasa.gov/data/search.html][LAADS]]). MODIS Data is
stored in Heirarchical Data Format (HDF).


** PVGIS

PVGIS (Photovoltaic Geographical Information System) is a research,
demonstration and policy-support instrument for geographical
assessment of the solar energy resource in the context of integrated
management of distributed energy generation.
- Computation of clear-sky global irradiation on a horizontal surface
- Sky obstruction by local terrain features (hills or mountains)
  calculated from the digital elevation model.
- Interpolation of the clear-sky index and computation of global
  irradiation on a horizontal surface.

Results available at http://re.jrc.ec.europa.eu/pvgis/apps4/pvest.php


** OpenWeatherMap

The [[http://openweathermap.org/][OpenWeatherMap service]] provides open current weather and forecast
that is available on our web-site for everybody and by API for
developers. Ideology of our service is inspired by OpenStreetMap and
Wikipedia that make information free and available for
everybody. OpenWeatherMap provides wide range of weather data
including current weather,forecast, precipitations, wind, clouds, data
from weather stations, lots of maps, analytics and many others. We
have own model of weather calculation that involves global
meteorological broadcast data, own WRF calculation for regions and
real-time data from more than 40,000 weather stations.

*** API
You need an [[http://openweathermap.org/appid][API key]].
- Current Weather data: [[http://openweathermap.org/current]]
- Historical data: [[http://openweathermap.org/history]]
- Weather stations: http://openweathermap.org/api_station

*** Pricing
 [[http://openweathermap.org/price]]


** [[http://www.dgi.inpe.br/CDSR/][INPE (Brasil)]]



** ADRASE - CIEMAT
Radiación solar media mensual, resolución aproximada de 5x5 km.
  - Media mensual y anual más probable durante un periodo de largo
    plazo (imágenes de satélite, modelo aproximadamente Heliosat)
  - Variabilidad esperada de los valores diarios mensuales: (series
    largas de datos de estaciones de AEMET y extrapolación espacial
    con IDW)
Disponible en [[http://adrase.es]]


* Weather Forecast
  :PROPERTIES:
  :CUSTOM_ID: forecast
  :END:

** [[http://www.ncdc.noaa.gov/model-data/numerical-weather-prediction][NCDC-NOAA]]

Data is available through the NOAA National Operational Model Archive
& Distribution System ([[http://nomads.ncdc.noaa.gov/][NOMADS]]). There is a [[http://nomads.ncdc.noaa.gov/thredds/catalog.html][Thredds server]].


*** [[http://www.emc.ncep.noaa.gov/gmb/gdas/][Global Data Assimilation System]] 

The Global Data Assimilation System (GDAS) is the system used by
the Global Forecast System (GFS) model to place observations into
a gridded model space for the purpose of starting, or
initializing, weather forecasts with observed data. GDAS adds the
following types of observations to a gridded, 3-D, model space:
surface observations, balloon data, wind profiler data, aircraft
reports, buoy observations, radar observations, and satellite
observations. GDAS data are available through NOMADS as both input
observations to GDAS and gridded output fields from GDAS. Gridded
GDAS output data can be used to start the GFS model. Due to the
diverse nature of the assimilated data types, input data are
available in a variety of data formats, primarily Binary Universal
Form for the Representation of meteorological data (BUFR) and
Institute of Electrical and Electronics Engineers (IEEE) binary.

*** [[http://www.emc.ncep.noaa.gov/index.php?branch=GFS][Global Forecast System (GFS)]]

The Global Forecast System (GFS) is a weather forecast model
produced by the National Centers for Environmental Prediction
(NCEP). Dozens of atmospheric and land-soil variables are
available through this dataset, from temperatures, winds, and
precipitation to soil moisture and atmospheric ozone
concentration. The entire globe is covered by the GFS at a base
horizontal resolution of 18 miles (28 kilometers) between grid
points, which is used by the operational forecasters who predict
weather out to 16 days in the future. Horizontal resolution drops
to 44 miles (70 kilometers) between grid point for forecasts
between one week and two weeks. The GFS model is a coupled model,
composed of four separate models (an atmosphere model, an ocean
model, a land/soil model, and a sea ice model), which work
together to provide an accurate picture of weather conditions.

*** [[http://www.ncdc.noaa.gov/model-data/global-ensemble-forecast-system-gefs][Global Ensemble Forecast System (GEFS)]]

The Global Ensemble Forecast System (GEFS) is a weather forecast
model made up of 21 separate forecasts, or ensemble members. The
National Centers for Environmental Prediction (NCEP) started the
GEFS to address the nature of uncertainty in weather observations,
which are used to initialize weather forecast models. The
proverbial butterfly flapping her wings can have a cascading
effect leading to wind gusts thousands of miles away. This extreme
example illustrates that tiny, unnoticeable differences between
reality and what is actually measured can, over time, lead to
noticeable differences between what a weather model forecast
predicts and reality itself. The GEFS attempts to quantify the
amount of uncertainty in a forecast by generating an ensemble of
multiple forecasts, each minutely different, or perturbed, from
the original observations. With global coverage, GEFS is produced
four times a day with weather forecasts going out to 16
days. Gridded data are available through NOMADS. NOMADS also
contributes GEFS ensemble data to the THORPEX Interactive Grand
Global Ensemble (TIGGE) by calculating a dozen WMO-required
variables and passing to the National Center for Atmospheric
Research (NCAR) for permanent archive. 

NOMADS also provides an additional tool, [[http://nomads.ncdc.noaa.gov/EnsProb/][the NOMADS Ensemble
Probability Tool]], which allows a user to query the multiple forecast
ensemble to determine the probability that a set of conditions will
occur at a given location using all of the GEFS ensemble members in
near real-time.

Many other forecast products are available at the [[http://www.emc.ncep.noaa.gov/GEFS/.php][GEFS homepage]].

*** [[http://www.ncdc.noaa.gov/data-access/model-data/model-datasets/north-american-mesoscale-forecast-system-nam][North American Model (NAM)]]
NAM is a regional weather forecast model covering North America down
to a horizontal resolution of 12km. Dozens of weather parameters are
available from the NAM grids, from temperature and precipitation to
lightning and turbulent kinetic energy.
*** [[http://www.ncdc.noaa.gov/data-access/model-data/model-datasets/rapid-refresh-rap][Rapid Refresh (RAP)]]
RAP is a regional weather forecast model of North America, with
separate subgrids (with different horizontal resolutions) within the
overall North America domain. RAP forecasts are generated every hour
with forecast lengths going out 18 hours.
*** [[http://www.ncdc.noaa.gov/data-access/model-data/model-datasets/rapid-update-cycle-ruc][Rapid Update Cycle (RUC)]]
RUC is a regional weather forecast model of the Continental United
States (CONUS) with forecast lengths going out 12 hours. RUC data are
no longer produced operationally by the National Centers for
Environmental Prediction (NCEP).


** WRF

*** Description
The [[http://www.wrf-model.org/index.php][Weather Research and Forecasting]] (WRF) Model is a
next-generation mesoscale numerical weather prediction system
designed to serve both operational forecasting and atmospheric
research needs. It features multiple dynamical cores, a
3-dimensional variational (3DVAR) data assimilation system, and a
software architecture allowing for computational parallelism and
system extensibility. WRF is suitable for a broad spectrum of
applications across scales ranging from meters to thousands of
kilometers.

The effort to develop WRF has been a collaborative partnership,
principally among the National Center for Atmospheric Research
(NCAR), the National Oceanic and Atmospheric Administration (the
National Centers for Environmental Prediction (NCEP) and the
Forecast Systems Laboratory (FSL), the Air Force Weather Agency
(AFWA), the Naval Research Laboratory, the University of Oklahoma,
and the Federal Aviation Administration (FAA). WRF allows
researchers the ability to conduct simulations reflecting either
real data or idealized configurations. WRF provides operational
forecasting a model that is flexible and efficient
computationally, while offering the advances in physics, numerics,
and data assimilation contributed by the research community.

*** Institutions
This system is used by [[http://wrf-model.org/plots/wrfrealtime.php][several institutions]]:

- NCAR ARW: 20 km CONUS: 72 h fcst from 00 Z initialization, and 48 h
  fcst from 12 Z initialization from 40 km Eta, mass coordinate. 36/12
  km CONUS/Central US two-way nested run: 48 h fcst from 00 Z
  initialization, initialization from 40 km Eta grib data, mass
  coordinates

- NCEP/EMC: WRF-NMM at 12 km horizontal resolution out to 84
  hours, 4 times a day; HiRes Window runs from WRF-NMM (5.2 km) and WRF-ARW (5.8 km).

- NOAA/GSD: 15 hr North American WRF runs, 13 km, hourly
  initialization, Gridpoint Statistical Interpolation (GSI) data
  assimilation; 15 hr CONUS WRF runs, 3 km, hourly initialization from RUC native-level coordinate.
 
- NOAA/NSSL: WRF-ARW, 4km, sub-CONUS, 36 h forecast

- National Observatory of Athens: 24km: 72h forecast from 00 Z and 12 Z initialization (European region)

- AFWA: Real time WRF forecast over North America (password required): 48 h, 00 Z 

- University of Illinois: Real time WRF forecast: 25 km (midwest region), 36 h, 00 Z initialization, mass coordinate 

- Millersville Univ, PA: 25 km Eastern US (east of Rockies): 36 h, mass coordinate 

- University of Utah, UT: 12.5 km Western US (west of Rockies): 48 h, mass coordinate


*** Meteogalicia

- Results from a WRF model freely available at the [[http://www.meteogalicia.es/web/modelos/threddsIndex.action][Thredds server]]

- Model WRF runs twice a day initialized at 00UTC (96 hours) and
  12UTC (84 hours).

- Three nested domains configured for 36km, 12km and 4km
  resolution.

- Spatial data:

  - 2D: [[http://mandeo.meteogalicia.es/thredds/catalogos/WRF_2D/catalog.html][WRF_2D/catalog.html]]

  - 3D: [[http://mandeo.meteogalicia.es/thredds/catalogos/WRF/catalog_grib.html][WRF/catalog_grib.html]]

- Time series: 
[[http://mandeo.meteogalicia.es/thredds/ncss/grid/wrf_2d_12km/fmrc/files/20130319/wrf_arw_det_history_d02_20130319_0000.nc4?var=swflx&point=true&latitude=42.13393&longitude=-1.652131][var=swflx&point=true&latitude=42.13393&longitude=-1.652131]]


*** BSC
El Barcelona Supercomputing Center usa este modelo para realizar
[[http://www.wire1002.ch/fileadmin/user_upload/Major_events/WS_Nice_2011/Spec._presentations/Jorba.pdf][short-term forecasting of solar irradiance]]. Se ha realizado una [[http://www.tdx.cat/handle/10803/129515][tesis
doctoral]] con el título "Sistema de pronóstico de radiación solar a
corto plazo a partir de un modelo meteorológico y técnicas de
post-proceso para España".


*** UPM
El [[http://artico.lma.fi.upm.es/][Grupo de Modelos y Software para el Medio Ambiente]] de la
Facultad de Informática de la UPM publica [[http://atmosfera.lma.fi.upm.es/mm5v3.6/][resultados gráficos]] de
la versión 3.6 de este modelo.


** MM5

The [[http://www.mmm.ucar.edu/mm5/][PSU/NCAR mesoscale model]] is a limited-area, nonhydrostatic or
hydrostatic (Version 2 only), terrain-following sigma-coordinate
model designed to simulate or predict mesoscale and regional-scale
atmospheric circulation. It has been developed at Penn State and
NCAR as a community mesoscale model and is continuously being
improved by contributions from users at several universities and
government laboratories.

The last major MM5 release (3.7) was December 2004, with the last bug
fix release in October 2006. Email support has been discontinued, and
online documentation and tutorials have been frozen.[1]

The Weather Research and Forecasting model (WRF) was designed as the
successor to MM5 and includes all capabilities available within the
MM5

*** Description 

The Fifth-Generation NCAR / Penn State Mesoscale Model (MM5) is
the latest in a series that developed from a mesoscale model used
by Anthes at Penn State in the early 70's that was later
documented by Anthes and Warner (1978). Since that time, it has
undergone many changes designed to broaden its usage. These
include (i) a multiple-nest capability, (ii) nonhydrostatic
dynamics, which allows the model to be used at a few-kilometer
scale, (iii) multitasking capability on shared- and
distributed-memory machines, (iv) a four-dimensional
data-assimilation capability, and (v) more physics options.

The model (known as MM5) is supported by several auxiliary
programs, which are referred to collectively as the MM5 modeling
system.  

Terrestrial and isobaric meteorological data are horizontally
interpolated (programs TERRAIN and REGRID) from a
latitude-longitude mesh to a variable high-resolution domain on
either a Mercator, Lambert conformal, or polar stereographic
projection. Since the interpolation does not provide mesoscale
detail, the interpolated data may be enhanced (program RAWINS or
little_r) with observations from the standard network of surface
and rawinsonde stations using either a successive-scan Cressman
technique or multiquadric scheme. Program INTERPF performs the
vertical interpolation from pressure levels to the sigma
coordinate system of MM5. Sigma surfaces near the ground closely
follow the terrain, and the higher-level sigma surfaces tend to
approximate isobaric surfaces. Since the vertical and horizontal
resolution and domain size are variable, the modeling package
programs employ parameterized dimensions requiring a variable
amount of core memory. Some peripheral storage devices are also
used.

Since MM5 is a regional model, it requires an initial condition as
well as lateral boundary condition to run. To produce lateral
boundary condition for a model run, one needs gridded data to
cover the entire time period that the model is integrated.



** ECMWF

The [[http://www.ecmwf.int/en/about][European Centre for Medium-Range Weather Forecasts]] (ECMWF, the
Centre) is an intergovernmental organisation supported by 34
States, based in Reading, west of London, in the United Kingdom.

ECMWF produces a suite of [[http://www.ecmwf.int/en/forecasts][operational forecasts]] for various lead
times:

- Medium-range forecast: comprises the high-resolution and the
  ensemble forecasts of weather, at the space and time-scales
  represented by the relevant model, up to 10 and 15 days ahead,
  respectively, and the associated uncertainty.
- Extended-range (monthly) forecast: comprises ensembles of
  individual forecasts and post-processed products of average
  conditions (e.g. weekly averages) up to 1 month ahead, and the
  associated uncertainty.
- Long-range forecast: comprises ensembles of individual forecasts
  and post-processed products of average conditions (e.g. monthly
  averages) up to 13 months ahead, and the associated uncertainty.

In addition re-forecasts are calculated operationally using the
current system configuration but applied to the weather over past
decades. 

Depending on the products [[www.ecmwf.int/products/catalogue/tariffs_examples.html][different tariffs]] may apply. Specific
data sets are available free of charge from the [[http://data-portal.ecmwf.int/][data server]],
subject to terms and conditions.


** AEMET

Dentro de las actividades de I+D+i de AEMET se encuadran los
modelos numéricos HIRLAM y HARMONIE, la predicción probabilítica y
la predicción inmediata. AEMET ofrece los resultados dentro de su
cartera de servicios según una [[https://sede.aemet.gob.es/documentos/es/servicios/publicos/AEMET/solicitudes/20060201.pdf][lista de tarifas]]. Según se recoge
en esta lista "el suministro de prestaciones a los organismos de
investigación, oficialmente reconocidos como tales, en la
realización de proyectos de investigación no lucrativos debe ser
realizada, por quien esté debidamente autorizado, en el modelo
establecido por el Instituto Nacional de Meteorología para este
fin."

*** Hirlam
[[http://www.aemet.es/es/eltiempo/prediccion/modelosnumericos/hirlam][Hirlam]] es un modelo hidrostático de puntos de rejilla con una
dinámica semilagrangiana, en el que son parametrizados los
procesos radiativos y los que suceden a escala sub-rejilla
(turbulencia, nubes y condensación, convección, intercambios de
agua y energía con la superficie…).

El estado inicial atmosférico, o análisis, se obtiene corrigiendo
una primera estimación (basada en una predicción a corto plazo
reciente), mediante la asimilación de observaciones convencionales
(procedentes de estaciones de superficie en tierra, barcos y
boyas, radiosondeos y aviones), así como los datos brutos medidos
por los instrumentos a bordo de los satélites meteorológicos,
mediante un método variacional tri o tetradimensional (3DVAR o
4DVAR). Los campos iniciales de superficie y suelo (temperatura
del agua del mar, espesor y cobertura de nieve, humedad y
temperaturas del suelo y subsuelo…) se describen gracias a un
sistema de análisis objetivo que utiliza diferentes tipos de
observaciones.

La cadena HIRLAM se ejecuta 4 veces al día en AEMET en 3 dominios
distintos: un área euroatlántica con 16km de resolución horizontal
y dos centradas en la Península Ibérica y Canarias de 5km de
resolución. El número de niveles en la vertical es de 40. Los
campos previstos del modelo global del Centro Europeo de
Predicción a Plazo Medio (CEPPM) se reciben 4 veces al día y se
utilizan como forzamientos en los contornos del dominio de
integración y para mejorar la descripción de la componente de
larga escala del análisis. Las observaciones utilizadas para
determinar el estado inicial atmosférico se reciben regularmente
gracias al sistema mundial de telecomunicaciones establecido por
la Organización Meteorológica Mundial.

En HIRLAM-AEMET 0.16° según el nivel seleccionado se puede acceder
a los siguientes parámetros:
 + Superficie: presión, precipitación, viento, nubosidad y temperatura
 + 850 hPa y 500 hPa: temperatura y geopotencial
 + 300 hPa: viento y geopotencial

En HIRLAM-AEMET 0.05° se puede seleccionar por C. Autónomas los
parámetros de superficie: temperatura, viento y precipitación.

En la pestaña CEPPM se puede seleccionar entre los parámetros de
presión en superficie y geopotencial de 500 hPa para tres zonas
del planeta: Atlántico Norte, Hemisferio Norte y Hemisferio Sur.

Alcances: los tres primeros días, a intervalos de 6 horas, para
HIRLAM-AEMET 0.16°, y los tres días siguientes, a intervalos de 24
horas, del modelo CEPPM. Para HIRLAM-AEMET 0.05° día y medio, a
intervalos de 3 horas.

*** Harmonie
Cuando se avanza hacia resoluciones de unos pocos kilómetros, los
efectos no hidrostáticos deben estar representados en los modelos
meteorológicos y algunos fenómenos que en resoluciones inferiores
deben ser parametrizados comienzan a ser descritos
explícitamente. En el año 2006, los Consorcios europeos de PNT
HIRLAM y ALADIN acordaron comenzar una cooperación para el
desarrollo de sistemas de muy alta resolución basados en modelos
no hidrostáticos.

El sistema HARMONIE, que se está desarrollando en HIRLAM, es el
resultado de esta colaboración y ha sido diseñado de forma
flexible, pudiendo ser utilizado en diferentes escalas espaciales:
desde la sinóptica hasta resoluciones inferiores a 1km. Además del
modelo de predicción, consta de un sistema de asimilación de datos
para la inicialización del estado atmosférico y de un módulo de
análisis de superficie. Tiene implementados diferentes conjuntos
de parametrizaciones físicas que resultan apropiados para cada
escala espacial. El núcleo de la dinámica no hidrostática
aprovecha los desarrollos obtenidos por el grupo ALADIN. Las
librerías de código se comparten entre el CEPPM, los Consorcios
HIRLAM y ALADIN y el Servicio Meteorológico francés.

El modelo HARMONIE en modo no hidrostático incluye 6 variables de
pronóstico para los procesos húmedos: vapor de agua, agua líquida,
cristales de hielo, lluvia, nieve y nieve granulada o
granizo. Esta versión del modelo se ejecuta diariamente en modo
experimental en AEMET sobre un área que cubre la península Ibérica
y Baleares a 2,5km de resolución horizontal y 65 niveles en la
vertical.

*** SAF  de Nowcasting

El [[http://www.nwcsaf.org/HD/MainNS.jsp][SAF de Nowcasting]] (NWC SAF), pertenece a la Red de Centros de
Aplicaciones Satelitales (Satellite Application Facilities, SAF)
que la organización europea para la explotación de los satélites
meteorológicos, EUMETSAT, tiene distribuidos por Europa, como
parte del segmento terrestre. Su objetivo es proporcionar
servicios operativos que optimicen el uso de datos de satélite
para la predicción inmediata y a muy corto plazo.

El NWC SAF está desarrollado por un Consorcio integrado los
Servicos Meteorológicos Nacionales de Francia, Suecia, Austria y
España, siendo liderado por AEMET.  El proyecto fue firmado en
diciembre de 1996 entre EUMETSAT y el entonces Instituto Nacional
de Meteorología, comenzando la fase de desarrollo en febrero
de 1997. Para conseguir su objetivo, el SAF de Nowcasting es el
responsable del desarrollo y mantenimiento de aplicaciones
software, así como de dar apoyo a los usuarios en el uso tanto del
software como de los productos finales. El NWC SAF está
considerado Centro de Excelencia para el Nowcasting en EUMETSAT.

Los productos desarrollados son aplicables a los satélites
meteorológicos geostacionarios MSG (Meteosat Second Generation) y
de órbita polar PPS (Tiros-NOAA y EPS-Metop). AEMET es responsable
de los productos MSG en aire claro, el de estimación de
precipitación convectiva y el de vientos en alta resolución.

Para plazos inferiores a 6 horas (1-3-6 horas), junto a los
modelos deterministas (CEPPM, HIRLAM y HARMONIE), la incorporación
del resto de herramientas (productos del NWC SAF, aplicaciones
operativas de nowcasting, observaciones de satélite, radar y
estaciones meteorológicas automáticas…), ha permitido ensayar
predicciones experimentales cuantitativas de las áreas (alrededor
de un punto) donde se esperaba precipitación intensa con
probabilidad del 60-80%, así como la cantidad de precipitación
esperada, hora de inicio de la precipitación/convección (+/- 30
minutos) y predicción del desplazamiento de los sistemas nubosos
responsables de la lluvia fuerte o convección severa.

**** [[http://www.nwcsaf.org/indexScientificDocumentation.html][Products]] 
- Cloud products
- Precipitating clouds
- Cconvective rainfall rate
- High resolution 
- Air mass analysis
- [...]

**** Nowcasting SAF User Policy

All current National Meteorological Services within the EUMETSAT
Member States and Co-operating States and those who in a future
shall become EUMETSAT Member States or Co-operating States, will
be automatically considered potential users.

Any other Organisation may apply to become a user through the
Leading Entity (emailing to NWC SAF Manager mafernandeza@aemet.es
and asanchezp@aemet.es). Decision will be taken by the Nowcasting
SAF according to the EUMETSAT Data Policy affecting the Nowcasting
SAF and will be communicated to the intended user accordingly.

*** Sistemas de Predicción por Conjuntos para la predicción probabilística
Para generar predicciones a medio plazo, entre 3 y 5 días, AEMET
postprocesa y utiliza las salidas del Sistema global de Predicción
por Conjuntos (Ensemble Prediction System, EPS), del Centro
Europeo de Predicción a Plazo Medio (CEPPM), basado en
perturbaciones del estado inicial atmosférico y de las
contribuciones de las parametrizaciones físicas del modelo. Para
la predicción probabilística en el corto plazo, hasta 48 horas,
AEMET es pionera en el desarrollo y ejecución experimental a
escala diaria de un Sistema de Predicción por Conjuntos, SREPS, de
mayor resolución (25km) y con 25 miembros, basado en la
integración de 5 modelos numéricos en área limitada diferentes
forzados con las predicciones de 5 modelos globales distintos. Con
ello se pretende muestrear las incertidumbres procedentes de los
errores de los modelos, las condiciones iniciales y las
condiciones de contorno.

*** Desarrollo de técnicas avanzadas de verificación

La verificación de las predicciones de los modelos meteorológicos
frente a observaciones forma parte de las cadenas operativas de
predicción numérica del tiempo ejecutadas en AEMET, tanto
deterministas como las basadas en predicción por conjuntos. Con
SREPS, AEMET diseñó, desarrolló y puso en funcionamiento un
sistema completo de postproceso de las salidas de sus miembros,
así como de verificación de las predicciones probabilísticas
generadas, que ha sido posteriormente implementado en el sistema
GLAMEPS de HIRLAM.

*** Métodos de adaptación estadística a las salidas de los modelos numéricos

A pesar del aumento significativo de su resolución y complejidad,
los modelos numéricos meteorológicos son representaciones
simplificadas de los procesos atmosféricos. Cuando se requieren
predicciones cuantitativas de variables tales como lluvia,
temperaturas extremas, etc. a nivel muy local, todavía se hace
necesario aplicar a sus salidas métodos de adaptación
estadística. AEMET viene trabajando en el desarrollo y puesta en
funcionamiento de diferentes métodos de adaptación estadística de
las salidas directas de los modelos desde hace más de dos décadas.

*** Herramientas para la identificación objetiva de estructuras convectivas

Una gran cantidad de los casos de lluvias intensas y vientos
fuertes que ocurren muy frecuentemente en España son producidos
por fenómenos convectivos, que en ocasiones llevan también
asociados granizo de gran tamaño e incluso tornados. A lo largo de
la última década, AEMET ha venido desarrollando nuevas
aplicaciones para analizar y caracterizar de forma objetiva en 2 y
3 dimensiones las estructuras convectivas.  El procedimiento
desarrollado integra diferentes fuentes de datos: radar, rayos,
satélite y salidas de modelos numéricos. También incluye un módulo
específico para estimar la probabilidad de granizo, así como la
extrapolación de las esctructuras convectivas. Las herramientas
han sido desarrolladas en el entorno del sistema McIDAS y generan
avisos gráficos a los predictores sobre la ocurrencia de este tipo
de fenómenos. Estos productos son de gran ayuda para la labor de
vigilancia y predicción inmediata llevada a cabo por los
predictores, tanto en los avisos de índole general como en la
predicción para sectores de usuarios específicos, como el
aeronáutico.



** forecast.io

*** Data sources
Forecast.io is backed by a wide range of data sources, which are
aggregated together statistically to provide the most accurate
forecast possible for a given location:

    - Dark Sky’s own hyperlocal precipitation forecasting system (id darksky), backed by radar data from the following systems:
      - The USA NOAA’s NEXRAD system (USA).
      - The UK Met Office’s NIMROD system (UK, Ireland).
      - (More coming soon.)
    - The USA NOAA’s LAMP system (USA, id lamp).
    - The UK Met Office’s Datapoint API (UK, id datapoint).
    - The Norwegian Meteorological Institute’s meteorological forecast API (global, id metno).
    - The USA NOAA’s Global Forecast System (global, id gfs).
    - The USA NOAA’s Integrated Surface Database (global, id isd).
    - The USA NOAA’s Public Alert system (USA, id nwspa).
    - The UK Met Office’s Severe Weather Warning system (UK, id metwarn).
    - Environment Canada’s Canadian Meteorological Center ensemble model (global, id cmc).
    - The US Navy’s Fleet Numerical Meteorology and Oceanography Ensemble Forecast System (global, id fnmoc).
    - The USA NOAA and Environment Canada’s North American Ensemble Forecast System (global, id naefs).
    - The USA NOAA’s North American Mesoscale Model (North America, id nam).
    - The USA NOAA’s Rapid Refresh Model (North America, id rap).
    - The Norwegian Meteorological Institute’s GRIB file forecast for Central Europe (Europe, id metno_ce).
    - The Norwegian Meteorological Institute’s GRIB file forecast for Northern Europe (Europe, id metno_ne).
    - Worldwide METAR weather reports (global, id metar).
    - The USA NOAA/NCEP’s Short-Range Ensemble Forecast (North America, id sref).
    - The USA NOAA/NCEP’s Real-Time Mesoscale Analysis model (North America, id rtma).
    - The USA NOAA/ESRL’s Meteorological Assimilation Data Ingest System (global, id madis).
      
*** API
The [[https://developer.forecast.io/docs/v2][Forecast API]] lets you query for most locations on the globe, and returns:

- Current conditions
- Minute-by-minute forecasts out to 1 hour (where available)
- Hour-by-hour forecasts out to 48 hours
- Day-by-day forecasts out to 7 days

*** Pricing policy
You can use the API in both commercial and non-commercial applications.

- The first thousand API calls you make every day are free, period.
- Every API call after that costs $1 per 10,000 (that is, 0.01¢).
- Credit us with a “Powered by Forecast” badge that links to http://forecast.io/ wherever you display data from the API.


** OpenWeatherMap

The [[http://openweathermap.org/][OpenWeatherMap service]] provides open current weather and forecast
that is available on our web-site for everybody and by API for
developers. Ideology of our service is inspired by OpenStreetMap and
Wikipedia that make information free and available for
everybody. OpenWeatherMap provides wide range of weather data
including current weather,forecast, precipitations, wind, clouds, data
from weather stations, lots of maps, analytics and many others. We
have own model of weather calculation that involves global
meteorological broadcast data, own WRF calculation for regions and
real-time data from more than 40,000 weather stations.

*** API

Our [[http://openweathermap.org/forecast][API]] can provide you with weather forecast for any location on the
Earth. The flexible algorithm of weather calculation let us get
weather data not only for cities but for any geographic
coordinates. It is important for megapolices, for example, where
weather is different on opposit city edges. You can get forecast data
every 3 hours or daily. The 3 hours forecast is calculating for 5
days. Daily forecast is calculating for 14 days. All weather data can
be obtained in JSON or XML format.

*** Pricing 
[[http://openweathermap.org/price]]


* Reanalysis
  :PROPERTIES:
  :CUSTOM_ID: reanalysis
  :END:

Reanalysis is a scientific method for developing a comprehensive
record of how weather and climate are changing over time. In it,
observations and a numerical model that simulates one or more
aspects of the Earth system are combined objectively to generate a
synthesized estimate of the state of the system. A reanalysis
typically extends over several decades or longer, and covers the
entire globe from the Earth’s surface to well above the
stratosphere. Reanalysis products are used extensively in climate
research and services, including for monitoring and comparing
current climate conditions with those of the past, identifying the
causes of climate variations and change, and preparing climate
predictions. Information derived from reanalyses is also being
used increasingly in commercial and business applications in
sectors such as energy, agriculture, water resources, and
insurance.

** NCDC-NOAA

*** [[http://www.ncdc.noaa.gov/model-data/climate-forecast-system-reanalysis-and-reforecast-cfsrr][Climate Forecast System Reanalysis and Reforecast (CFSRR)]]

The Climate Forecast System (CFS) is a model representing the
global interaction between the Earth's oceans, land, and
atmosphere. Produced by several dozen scientists under guidance
from the National Centers for Environmental Prediction (NCEP),
this model offers hourly data with a horizontal resolution down to
one-half a degree (approximately 56km) around the Earth for many
variables. CFS uses the latest scientific approaches for
taking-in, or assimilating, observations from many data sources:
surface observations, upper air balloon observations, aircraft
observations, and satellite observations. The Climate Forecast
System Reanalysis (CFSR) is an effort to generate a uniform,
continuous, and best-estimate record of the state of the
ocean-atmosphere for use in climate monitoring and
diagnostics. The method keeps the model’s software constant and
runs the model retrospectively, from 1979 through the present. In
addition to the reanalyses efforts, the CFS model was also used to
generate a Reforecast of past weather forecasts. These reforecasts
help us better understand the model's ability to produce accurate
weather forecasts.

*** [[http://www.ncdc.noaa.gov/model-data/reanalysis-1-reanalysis-2][Reanalysis-1 / Reanalysis-2]]

The National Centers for Environmental Prediction (NCEP) is
involved with two global reanalysis projects in joint ventures
with other organizations. The first is the NCEP/NCAR Reanalysis
(Reanalysis-1), a global reanalysis of atmospheric data spanning
1948 to present. It was created in cooperation with the National
Center for Atmospheric Research (NCAR). The second project is the
NCEP/DOE Reanalysis (Reanalysis-2) project, a global reanalysis of
atmospheric data spanning 1979 to present. It was created in
cooperation with the Department of Energy (DOE). Many data sources
went into the generation of both reanalyses: surface observations,
upper-air balloon observations, aircraft observations, and
satellite observations. Data from both reanalyses are available as
a global set of gridded weather data at a 2.5 degree by 2.5 degree
horizontal resolution. The main difference between these two
global reanalysis projects is the starting date of their period of
records. The year 1979 was chosen as a beginning date with
Reanalysis-2 as it coincides with the date of modern satellite
weather ingest. Reanalysis-1 begins in the year 1948, and the data
input pattern, better known as data assimilation, changes over the
course of this reanalysis, making it an inconsistent (though still
scientifically valid) reanalysis record due to there being no
satellite ingest in the early part of the Reanalysis-1 dataset.


** ENSEMBLES

[[Http://old.ecmwf.int/research/EU_projects/ENSEMBLES/index.html][ENSEMBLES]] is an EU-funded Integrated Project that intends to
develop an ensemble prediction system for climate change based on
the principal state-of-the-art, high resolution, global and
regional Earth System models developed in Europe, validated
against quality controlled, high resolution gridded datasets for
Europe, to produce for the first time, an objective probabilistic
estimate of uncertainty in future climate at the seasonal to
decadal and longer timescales.

This ensemble prediction system will be used to quantify and
reduce the uncertainty in the representation of physical,
chemical, biological and human-related feedbacks in the Earth
System (including water resource, land use, and air quality
issues, and carbon cycle feedbacks). 

[[http://old.ecmwf.int/research/EU_projects/ENSEMBLES/data/data_dissemination.htmlhttp://www.ecmwf.int/research/EU_projects/ENSEMBLES/data/data_dissemination.html][Data]] is available free of charge. There is a [[http://ensembles.ecmwf.int/thredds/catalog.html][Thredds server]].


** reanalyses.org
Using a collaborative Wiki framework, the goal of [[http://reanalyses.org][reanalyses.org]]
is to facilitate comparison between reanalysis and observational
datasets. Evaluative content provided by reanalysis developers,
observationalists, and users; and links to detailed data
descriptions, data access methods, analysis and plotting tools,
and dataset references are available. Discussions of the recovery
of observations to improve reanalyses is also a focus. The wiki
framework encourages scientific discussion between members of
reanalyses.org and other reanalysis users. 

#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
#+LATEX_HEADER: \usepackage[hyperref,x11names]{xcolor}
#+LATEX_HEADER: \hypersetup{colorlinks=true,urlcolor=SteelBlue4,linkcolor=Firebrick4}

